export default {
  CREATE_PLAYLIST: "CREATE_PLAYLIST",
  UPDATE_PLAYLIST: "UPDATE_PLAYLIST",
  LOAD_PLAYLISTS: "LOAD_PLAYLISTS",
  GET_PLAYLIST_BY_ID: "GET_PLAYLIST_BY_ID",
  
  ADD_VIDEO_INTO_PLAYLIST: "ADD_VIDEO_INTO_PLAYLIST",

  
  GET_KEYWORDS: "GET_KEYWORDS",
  CREATE_KEYWORDS: "CREATE_KEYWORDS"
};
